config/routes.rb
Rails.application.routes.draw do

  resources :sleeps

  resources :alarms

  resources :workouts

  resources :workout_types

  resources :users

  resources :sessions

  resources :goals

  resources :bands

  resources :band_types

  get '' => 'static_pages#home'
  get 'users/edit/:id' => 'users#edit', :as => :edit_current_user
  get 'users/new' => 'users#new', :as => :signup
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login

  get '/users/disable_user/:id/:active' => 'users#disable_user'
  get 'users/search' => 'users#search'

  get 'goal/history/:id' => 'goals#history'
  get 'band_data' => 'band_data#index'
  get 'share/:id' => 'static_pages#share'
  post 'band_data.json' => 'band_data#create'
  get 'dashboard' => 'static_pages#dashboard'
  get 'icons' => 'static_pages#icons'
  
  get 'sleep/awake/:id' => 'sleeps#awake'

  get 'workout/finish/:id' => 'workouts#finish'

end

app/models/alarm.rb
class Alarm < ActiveRecord::Base
  
  belongs_to :user

  before_create :set_values
  before_update :set_values

  def self.get_days
    days = Array.new
    days << ['All days', 0]
    days << ['Monday', 1]
    days << ['Tuesday', 2]
    days << ['Wednesday', 3]
    days << ['Thursday', 4]
    days << ['Friday', 5]
    days << ['Saturday', 6]
    days << ['Sunday', 7]
    days
  end

  def set_values   
    case self.day_week
      when '0'
        self.day_week = 'All days'
      when '1'
        self.day_week = 'Monday'
      when '2'
        self.day_week = 'Tuesday'
      when '3'
        self.day_week = 'Wednesday'
      when '4'
        self.day_week = 'Thursday'
      when '5'
        self.day_week = 'Friday'
      when '6'
        self.day_week = 'Saturday'
      when '7'
        self.day_week = 'Sunday'
    end
  end

end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy] 

  respond_to :html  
  def index 
    @alarms = Alarm.all
    respond_with(@alarms)
  end

  def show
    respond_with(@alarm)
  end

  def new
    @alarm = Alarm.new
    @days = Alarm.get_days
    respond_with(@alarm)
  end

  def edit
    @days = Alarm.get_days
  end

  def create
    @alarm = Alarm.new(alarm_params)
    @alarm.user_id = current_user.id
    @alarm.save
    respond_with(@alarm)
  end

  def update
    @alarm.update(alarm_params)
    respond_with(@alarm)
  end

  def destroy
    @alarm.destroy
    respond_with(@alarm)
  end

  private
    def set_alarm
      @alarm = User.find(current_user.id).alarms.find(params[:id])
    end

    def alarm_params
      params.require(:alarm).permit(:user_id, :day_week, :alarm_hour, :state, :name)
    end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/views/alarms/_form.html.erb
<%= form_validated_for(@alarm) do |f| %>
  
  <div class="form-group">
    <%= f.label :type %><br>    
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :day_week %><br>    
    <%= f.select :day_week, @days, {}, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :alarm_hour %><br>
    <%= f.datetime_select :alarm_hour, {:discard_day => true, :discard_month => true, :discard_year => true} %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.check_box :state, :class => 'icheckbox_flat-greem checked' %>
  </div>
  <div class="actions" align="right">
    <%= f.submit (@alarm.new_record? ? 'Create Alarm' : 'Update Alarm'),:class => 'btn bg-green'%>
  </div>  

<% end %>

app/views/alarms/alert_alarm.html.erb
<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>        
      </div>
    </div>
  </div>
</div>

app/views/alarms/edit.html.erb
<div class="container ">  
  <div class="col-xs-3 col-lg-3"></div>
    <div class="col-lg-6">
		<h1>Editing alarm</h1><br>
			<%= render 'form' %>
			<%= link_to 'Show', @alarm %> 
			<%= link_to 'Back', alarms_path %>
	</div>
  </div>
</div>

app/views/alarms/index.html.erb
<div class="container ">  
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">List of alarms</h3>
        <table class="table no-margin">
        <thead>
          <tr>
            <th>Type</th>
            <th>Day week</th>
            <th>Alarm hour</th>
            <th>State</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @alarms.each do |alarm| %>
            <tr>
              <td><%= alarm.name %></td>
              <td><%= alarm.day_week %></td>
              <td><%= alarm.alarm_hour.strftime("%H : %M")%></td>
              <td><%= alarm.state %></td>
              <td><%= link_to 'Show', alarm, :class => 'btn btn-info' %></td>
              <td><%= link_to 'Edit', edit_alarm_path(alarm), :class => 'btn btn-warning'  %></td>
              <td><%= link_to 'Destroy', alarm, :class => 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


<br>
<div align="right">
  <%= link_to 'New Alarm', new_alarm_path , :class => 'btn btn-success' %><br><br>
</div>

</div>

app/views/alarms/new.html.erb
<div class="container ">  
  <div class="col-xs-3 col-lg-3"></div>
    <div class="col-lg-6">
	  <h1>New alarm</h1><br>
	    <%= render 'form' %>		
    </div>
  </div>
</div>

app/views/alarms/show.html.erb
<div class="container ">  
  <div class="panel panel-primary">
    <div class="panel-heading" align="center"><h1><strong>Alarm</strong></h1></div>
    <div class="panel-body">  
     <center> <table class="table table-user-information">
        <tbody>
        	<tr>
            <td><strong>Type</strong></td>
            <td><%= @alarm.name %></td>
          <tr>
          <tr>
            <td><strong>Day week</strong></td>
            <td><%= @alarm.day_week %></td>
          <tr>

          <tr>
            <td><strong>Alarm hour</strong></td>
            <td><%= @alarm.alarm_hour  %></td>
          </tr>

          <tr>
            <td><strong>State</strong></td>
            <td><%= @alarm.state %></td>
          </tr>
      
          <th>
            <td></td>

          </th>
      </tbody>
    </table></center>

<div align="right">
  <%= link_to 'Edit', edit_alarm_path(@alarm), :class =>'btn bg-yellow' %> &nbsp;
  <%= link_to 'Back', alarms_path  , :class =>'btn btn-default'%>
    
</div>
</div>



</div>

</div><br>