config/routes.rb
Rails.application.routes.draw do

  resources :sleeps

  resources :alarms

  resources :workouts

  resources :workout_types

  resources :users

  resources :sessions

  resources :goals

  resources :bands

  resources :band_types

  get '' => 'static_pages#home'
  get 'users/edit/:id' => 'users#edit', :as => :edit_current_user
  get 'users/new' => 'users#new', :as => :signup
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login

  get '/users/disable_user/:id/:active' => 'users#disable_user'
  get 'users/search' => 'users#search'

  get 'goal/history/:id' => 'goals#history'
  get 'band_data' => 'band_data#index'
  get 'share/:id' => 'static_pages#share'
  post 'band_data.json' => 'band_data#create'
  get 'dashboard' => 'static_pages#dashboard'
  get 'icons' => 'static_pages#icons'
  
  get 'sleep/awake/:id' => 'sleeps#awake'

  get 'workout/finish/:id' => 'workouts#finish'

end

app/controllers/band_types_controller.rb
class BandTypesController < ApplicationController
  before_action :set_band_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @band_types = BandType.all
    respond_with(@band_types)
  end

  def show
    respond_with(@band_type)
  end

  def new
    @band_type = BandType.new
    respond_with(@band_type)
  end

  def edit
  end

  def create
    @band_type = BandType.new(band_type_params)
    @band_type.save
    respond_with(@band_type)
  end

  def update
    @band_type.update(band_type_params)
    respond_with(@band_type)
  end

  def destroy
    @band_type.destroy
    respond_with(@band_type)
  end

  private
    def set_band_type
      @band_type = BandType.find(params[:id])
    end

    def band_type_params
      params.require(:band_type).permit(:model)
    end
end

app/helpers/band_types_helper.rb
module BandTypesHelper
end

app/views/band_types/_form.html.erb
<%= form_for(@band_type) do |f| %>
  <% if @band_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band_type.errors.count, "error") %> prohibited this band_type from being saved:</h2>

      <ul>
      <% @band_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/band_types/edit.html.erb
<h1>Editing band_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @band_type %> |
<%= link_to 'Back', band_types_path %>

app/views/band_types/index.html.erb
<h1>Listing band_types</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @band_types.each do |band_type| %>
      <tr>
        <td><%= band_type.model %></td>
        <td><%= link_to 'Show', band_type %></td>
        <td><%= link_to 'Edit', edit_band_type_path(band_type) %></td>
        <td><%= link_to 'Destroy', band_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band type', new_band_type_path %>

app/views/band_types/new.html.erb
<h1>New band_type</h1>

<%= render 'form' %>

<%= link_to 'Back', band_types_path %>

app/views/band_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @band_type.model %>
</p>

<%= link_to 'Edit', edit_band_type_path(@band_type) %> |
<%= link_to 'Back', band_types_path %>