config/routes.rb
Rails.application.routes.draw do

  resources :sleeps

  resources :alarms

  resources :workouts

  resources :workout_types

  resources :users

  resources :sessions

  resources :goals

  resources :bands

  resources :band_types

  get '' => 'static_pages#home'
  get 'users/edit/:id' => 'users#edit', :as => :edit_current_user
  get 'users/new' => 'users#new', :as => :signup
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login

  get '/users/disable_user/:id/:active' => 'users#disable_user'
  get 'users/search' => 'users#search'

  get 'goal/history/:id' => 'goals#history'
  get 'band_data' => 'band_data#index'
  get 'share/:id' => 'static_pages#share'
  post 'band_data.json' => 'band_data#create'
  get 'dashboard' => 'static_pages#dashboard'
  get 'icons' => 'static_pages#icons'
  
  get 'sleep/awake/:id' => 'sleeps#awake'

  get 'workout/finish/:id' => 'workouts#finish'

end

app/controllers/workout_types_controller.rb
class WorkoutTypesController < ApplicationController
  before_action :set_workout_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workout_types = WorkoutType.all
    respond_with(@workout_types)
  end

  def show
    respond_with(@workout_type)
  end

  def new
    @workout_type = WorkoutType.new
    respond_with(@workout_type)
  end

  def edit
  end

  def create
    @workout_type = WorkoutType.new(workout_type_params)
    @workout_type.save
    respond_with(@workout_type)
  end

  def update
    @workout_type.update(workout_type_params)
    respond_with(@workout_type)
  end

  def destroy
    @workout_type.destroy
    respond_with(@workout_type)
  end

  private
    def set_workout_type
      @workout_type = WorkoutType.find(params[:id])
    end

    def workout_type_params
      params.require(:workout_type).permit(:typename, :outside)
    end
end

app/helpers/workout_types_helper.rb
module WorkoutTypesHelper
end

app/views/workout_types/_form.html.erb
<%= form_for(@workout_type) do |f| %>
  <% if @workout_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_type.errors.count, "error") %> prohibited this workout_type from being saved:</h2>

      <ul>
      <% @workout_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typename %><br>
    <%= f.text_field :typename %>
  </div>
  <div class="field">
    <%= f.label :outside %><br>
    <%= f.check_box :outside %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_types/edit.html.erb
<h1>Editing workout_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_type %> |
<%= link_to 'Back', workout_types_path %>

app/views/workout_types/index.html.erb
<h1>Listing workout_types</h1>

<table>
  <thead>
    <tr>
      <th>Typename</th>
      <th>Outside</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_types.each do |workout_type| %>
      <tr>
        <td><%= workout_type.typename %></td>
        <td><%= workout_type.outside %></td>
        <td><%= link_to 'Show', workout_type %></td>
        <td><%= link_to 'Edit', edit_workout_type_path(workout_type) %></td>
        <td><%= link_to 'Destroy', workout_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout type', new_workout_type_path %>

app/views/workout_types/new.html.erb
<h1>New workout_type</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_types_path %>

app/views/workout_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typename:</strong>
  <%= @workout_type.typename %>
</p>

<p>
  <strong>Outside:</strong>
  <%= @workout_type.outside %>
</p>

<%= link_to 'Edit', edit_workout_type_path(@workout_type) %> |
<%= link_to 'Back', workout_types_path %>