config/routes.rb
Rails.application.routes.draw do

  resources :sleeps

  resources :alarms

  resources :workouts

  resources :workout_types

  resources :users

  resources :sessions

  resources :goals

  resources :bands

  resources :band_types

  get '' => 'static_pages#home'
  get 'users/edit/:id' => 'users#edit', :as => :edit_current_user
  get 'users/new' => 'users#new', :as => :signup
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login

  get '/users/disable_user/:id/:active' => 'users#disable_user'
  get 'users/search' => 'users#search'

  get 'goal/history/:id' => 'goals#history'
  get 'band_data' => 'band_data#index'
  get 'share/:id' => 'static_pages#share'
  post 'band_data.json' => 'band_data#create'
  get 'dashboard' => 'static_pages#dashboard'
  get 'icons' => 'static_pages#icons'
  
  get 'sleep/awake/:id' => 'sleeps#awake'

  get 'workout/finish/:id' => 'workouts#finish'

end

app/models/band.rb
class Band < ActiveRecord::Base
  belongs_to :user
  belongs_to :Band_type

  before_create :set_values
  before_update :set_values

  validates :color, presence: true
  validates :Band_type_id, presence: true

  def self.get_types
    type = Array.new
    BandType.all.each do |x|
      type << [x.model, x.id]
    end

    type
  end

  def self.get_color
    colors = Array.new
    colors << ['Blue', 1]
    colors << ['Green', 2]
    colors << ['Red', 3]
    colors
  end

  def set_values
    val = self.color
    case val
      when '1'
        self.color = 'blue'
      when '2'
        self.color = 'green'
      when '3'
        self.color = 'red'
      else
        self.color = 'blue'
    end
  end
end

app/models/band_type.rb
class BandType < ActiveRecord::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bands = Band.where(user_id: current_user.id)
    respond_with(@bands)
  end

  def show
    respond_with(@band)
  end

  def new
    @types = Band.get_types
    @colors = Band.get_color
    @band = Band.new
    respond_with(@band)
  end

  def edit
    @band.user_id = current_user.id
    @types = Band.get_types
    @colors = Band.get_color
    @band = Band.find(params[:id])
    respond_with(@band)
  end

  def create
    @band = Band.new(band_params)
    @band.user_id = current_user.id
    @band.save
    respond_with(@band)
  end

  def update
    @band.update(band_params)
    respond_with(@band)
  end

  def destroy
    @band.destroy
    respond_with(@band)
  end

  private
    def set_band
      @band = Band.find(params[:id])
    end

    def band_params
      params.require(:band).permit(:color, :user_id, :Band_type_id)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_validated_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
        <%= f.label :color %><br>
        <%= f.select :color, @colors, {}, {class: 'form-control'}%>
     </div>

  <div class="form-group">
    <%= f.label :Band_type_id %><br>
    <%= f.text_field :Band_type_id %>
  </div>
  <div class="actions" align="left">
    <%= f.submit "OK", :class => 'btn btn-warning'%>
  </div>

<% end %>

app/views/bands/edit.html.erb
<div class="container ">  
  <div class="col-xs-3 col-lg-3"></div>
    <div class="col-lg-6">

    	<h2>Edit your band</h2>
      <%= form_validated_for(@band) do |f| %>

          <div class="form-group">
            <%= f.label :color %><br>
            <%= f.select :color, @colors, {}, {class: 'form-control'}%>
          </div>

          <div class="form-group">
            <%= f.label :Band_type_id %><br>
            <%= f.select :Band_type_id, @types, {}, {class: 'form-control'}%>
          </div>
          <div class="actions" align="left">
            <%= f.submit "Edit Band", :class => 'btn btn-warning'%><%= link_to 'Back', bands_path, {class: "btn btn-default", style: "float:right;"} %>
          </div><br>
      <% end %>
    </div>
  </div>
</div>

app/views/bands/index.html.erb
<div class="container ">  
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">List of bands</h3>
      <table class="table no-margin">
        <thead >
          <tr>
            <th>User</th>
            <th>Color</th>
            <th>Band type</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bands.each do |band| %>
            <tr>
              <td><%= band.user.email %></td>

              <td><%= band.color %></td>
              
              <td><%= band.Band_type.model %></td>
              <td><%= link_to 'Show', band ,{class: "btn btn-info"}%></td>
              <td><%= link_to 'Edit', edit_band_path(band),class: "btn btn-warning" %></td>
              <td><%= link_to 'Delete', band , class: "btn btn-danger",  method: :delete, data: { confirm: 'Are you sure?' }    %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  <br>
  <div align="right">
    <%= link_to 'New Band', new_band_path, :class => 'btn btn-success' %>
  </div><br>
</div>

app/views/bands/new.html.erb
<div class="container ">  
  <div class="col-xs-3 col-lg-3"></div>
    <div class="col-lg-6">

    	<h2>Register your New band</h2><br>

      <%= form_validated_for(@band) do |f| %>

          <div class="form-group">
            <%= f.label :color %><br>
            <%= f.select :color, @colors, {}, {class: 'form-control'}%>
          </div>

          <div class="form-group">
            <%= f.label :Band_type_id %><br>
            <%= f.select :Band_type_id, @types, {}, {class: 'form-control'}%>
          </div>
          <div class="actions" align="left">
            <%= f.submit "New Band", :class => 'btn btn-success'%><%= link_to 'Back', bands_path, {class: "btn btn-default", style: "float:right;"} %>
          </div><br>

      <% end %>
    </div>
  </div>
</div>

app/views/bands/show.html.erb
<div class="container ">  
  <div class="panel panel-primary">
    <div class="panel-heading" align="center"><h1><strong>Band Profile</strong></h1></div>
    <div class="panel-body">  
       <center> <table class="table table-user-information">
        <tbody>
          <tr>
            <td><strong>User</strong></td>
            <td><%= current_user.name %></td>
          <tr>
          <tr>
            <td><strong>Model</strong></td>
            <td><%= @band.Band_type.model %></td>
          <tr>
          <tr>
            <td><strong>Color</strong></td>
          <%if @band.color == 'green' || @band.color == '2'%>
            <td style="background-color: rgb(0, 166, 90); border-color: rgb(0, 166, 90); wigth: 20px;"></td>
          <%end%>
          <%if @band.color == 'blue' || @band.color == '1'%>
            <td style="background-color: rgb(0, 115, 183); border-color: rgb(0, 115, 183); wigth: 20px;"></td>
          <%end%>
          <%if @band.color == 'red' || @band.color == '3'%>
            <td style="background-color: rgb(221, 75, 57); border-color: rgb(221, 75, 57); wigth: 20px;"></td>
          <%end%>        
          <tr>
</tbody>
    </table></center>
    <div align="center">
      <%= link_to 'Edit', edit_band_path(@band), :class => 'btn btn-warning' %> 
      <%= link_to 'Back', bands_path, :class => 'btn btn-default' %></div>
    </div>

</div>    
  
    </div>



<!--<p>
  <strong>Model:</strong>
  <%= @band.Band_type %>
</p>
-->